### ISSUE TITLE
Wrong table names

### ISSUE THREAD

**Issue by opi99** [datamintsGmbH/datamints_locallang_builder#1]
The tableprefix was somewhere changed now ext_tables.sql have
`tx_datamintslocallangbuilder_domain_model_extension`
but the code uses
`tx_locallangbuilder_domain_model_extension`

So opening lists mode leads to the error
`Table 'vagrant.tx_locallangbuilder_domain_model_extension' doesn't exist`

**Comment by opi99** [comment]
TYPO3: 9.5.26
Extensionversion: 1.0.5

**Comment by weisgerberm** [comment]
@opi99 Thank you. Please upgrade to Extension-Version 1.0.7. There should be no old tablenames like "tx_locallangbuilder". Maybe you have to clear your system cache after upgrading.
