### ISSUE TITLE
Incorrect integer value: 'yes' for column 'approved' at row 1

### ISSUE THREAD

**Issue by opi99** [datamintsGmbH/datamints_locallang_builder#3]
From specification the approved field is string yes|no http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#approved 
But it gets read as string without conversion to bool

`$translationValue->setApproved($domElement->getAttribute('approved'));`

Later while try tow rite into DB the string can't be converted to smallint as defined in the ext_tables.sql

`approved smallint(5) unsigned DEFAULT '0' NOT NULL,`

**Comment by opi99** [comment]
The setter of the TranslationValue Model could also get TypeHinting in modern PHP

**Comment by datamints** [comment]
Thank you, its fixed in Version 1.0.9

**Comment by opi99** [comment]
Did you forget to push the commits? No 1.0.9 tag exists. ;)

**Comment by weisgerberm** [comment]
I forgot to merge the dev-branch into master. Thanks :)

**Comment by opi99** [comment]
Ah, thanks.
BTW: Commits with whitespace changes on every line are a bit hard to read, it's better to use 2 commit, one for whitespace and one for the real issue.
