### ISSUE TITLE
Update for Typo3 v11

### ISSUE THREAD

**Issue by ReneReiterer** [datamintsGmbH/datamints_locallang_builder#6]
Hello,

do you have any plans to update the extension to typo3 v11?

**Comment by weisgerberm** [comment]
Hi,

Yeah, I'll check it out soon. I haven't tried TYPO3 11 yet, so I don't know what or whether I need to adjust something.

**Comment by weisgerberm** [comment]
> Hello,
> 
> do you have any plans to update the extension to typo3 v11?

Hi,

please update to version 1.0.18 for TYPO3 11 support
